"""Core Solo 2 device library, standalone package and CLI."""

from .clients import Solo2AdminClient, Solo2FidoClient, Solo2SecretsClient
from .admin import AdminCommand, AdminSession, DeviceDiagnostics, RebootMode
from .device import (
    DeviceInfo,
    DeviceMode,
    DeviceStatus,
    FirmwareCapabilities,
    Solo2Descriptor,
    Solo2Device,
    SoloDevice,
    firmware_supports_extended_applets,
    format_firmware_full,
    format_firmware_version,
)
from .discovery import (
    DeviceSnapshot,
    DeviceWatcher,
    list_bootloader_descriptors,
    list_descriptors,
    list_devices,
    list_regular_descriptors,
    open_bootloader,
    open_device,
)
from .errors import Solo2Error, Solo2NotFoundError, Solo2TransportError
from .fido2 import Fido2Credential, Fido2PinStatus, Fido2Session
from .pcsc import pcsc_available, should_prefer_ccid
from .provisioner import GeneratedKey, ProvisionerSession
from .secrets import (
    Algorithm,
    Credential,
    OATHBridge,
    OATHError,
    OATHPINRequired,
    OATHTouchRequired,
    OtherKind,
    OtpKind,
    OtpResult,
    SecretsAppProtocol,
    SecretsAppStatus,
    SecretsSession,
    encode_password_only_label,
    is_password_only_label,
    strip_password_only_label,
)

__all__ = [
    "AdminCommand",
    "AdminSession",
    "Algorithm",
    "Credential",
    "DeviceInfo",
    "DeviceDiagnostics",
    "DeviceSnapshot",
    "DeviceMode",
    "DeviceStatus",
    "DeviceWatcher",
    "FirmwareCapabilities",
    "Fido2Credential",
    "Fido2PinStatus",
    "Fido2Session",
    "GeneratedKey",
    "OATHBridge",
    "OATHError",
    "OATHPINRequired",
    "OATHTouchRequired",
    "OtherKind",
    "OtpKind",
    "OtpResult",
    "ProvisionerSession",
    "RebootMode",
    "SecretsAppProtocol",
    "SecretsAppStatus",
    "SecretsSession",
    "Solo2AdminClient",
    "Solo2Descriptor",
    "Solo2Device",
    "Solo2Error",
    "Solo2FidoClient",
    "Solo2NotFoundError",
    "Solo2SecretsClient",
    "Solo2TransportError",
    "SoloDevice",
    "firmware_supports_extended_applets",
    "format_firmware_full",
    "format_firmware_version",
    "list_bootloader_descriptors",
    "list_descriptors",
    "list_devices",
    "list_regular_descriptors",
    "open_bootloader",
    "open_device",
    "pcsc_available",
    "should_prefer_ccid",
    "encode_password_only_label",
    "is_password_only_label",
    "strip_password_only_label",
]
